airbnb:
  outputs:
    dev:
      type: snowflake
      account: UZBTQZO-FB12797
      user: dbt

      role: TRANSFORM
      private_key: "-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIFJDBWBgkqhkiG9w0BBQ0wSTAxBgkqhkiG9w0BBQwwJAQQevnGDU+urDDtz+mY
6j1+AAICCAAwDAYIKoZIhvcNAgkFADAUBggqhkiG9w0DBwQIgoqnOP37YdwEggTI
+U5F53WrixYrxsDtFYdFCI1S6beih4VAY9vYfLQ2LD36Mj3NSRJhrd1F/gn5kLbj
twZycAbQr/gdlzt6bqUAdPYi8V0dlUb+Htz+HVMYOIGH+xA2oS4zvvTIOrtMN43S
bigCKuCnNRpt843GmElhwRgxBXmVOYfEGDxG6FT9yYN06CjLWuX5TzzR7E6r7G6y
Kye6KF3OxtnOMFReInpI4oUSA9z4soE9EC6Q47S8Kc5uSFp6tGgtG1E08eWfZIW0
oXrpTEqiRx/dZnvwXhucX1P/H7NdBOEMxWth1Uq0LlVEvORr2LQjlPFtpgzCL8R6
gBb7SrPwlCHu0Uja8esJ1JzpXHwkCiHKS4X4hGWDjP1+EgstNjgUmCgSEZZnwKDR
aXSGDOtcok/FTfMuKrkLlRj+Ti+7L+1uxkfQ9ojj1gPRFuxAJamu89Ck/LOGL9Hi
uMsrpSJEgWlv2RJcfy659nxIdJ59dR6LwW8+pailNNeetuftQOZG1aEze/zAbQT6
cMwWJpGIVmOnHHO4iBvV/pEcKGnNpEc9dfMPiC8g23mZAl7LEwGMY/ICpOP8CzGe
hhi42oXY8aFmfDRmvzTDQjWzbsav7nlBF2e9c5niOfbSUphZKRyMcDrrG8gvSEmx
a3kCDR0PjRRQ4WfxfN49ftbwZkN9JzbDNlqeCHi2bDftwIlgGYE8TnI0DrKwmXez
ahNP1ekUxS5+5WXc66IE6+3ZZ0z5V8sRvkw1ykwbmiknl1Ooein4wJ5vYWyLYg5D
4kSAlMKSh+BlSB0+8WPtabBqh9wj/FtkC9xiHkHUxJ7BPGIqYV8cDiRdXrjOwHSU
AKoKErqOihVGjvEIe27IHM3n1Ceny8lJXnhyk1rzu4bhZEgeT1co6a0WP7vwp1Db
4gXFM038yJEpSJ17N6NfG6vuKTMQR6zG43mh6hk1ahBcLH8EXaf8uu0plOGONSDs
ZgI5/Y9Cu2+z9qRLy4k5vZvY1T0OcNXDU1Oz3KEUw2odpH+ApRR6L/xT9tkHe+xe
vz4BVxsDLHtFfK3DNtK2JXzh9hWwxyo/M6kcSCyS7k3uVri34Qki30NM+fESz6O+
uAbxsHjuffOAUYs6IXPZRrW5At9QXEh+89qXUHWDAlZfHhXEnacZtBU5bGdtq8jA
LVgv5o71TM7Y2QE2VC95yUnsMl6zKMOR1ogdh7dDl8j03nEHQ4bsby6XCjlpkQOF
hOYWENPf5kPD+p9xccJp7rnQLWn/CvGXrS4zk63tkPbwtYsmZI3q/eAp02lnqb9e
jpZjXfV9xqrn7EBG+EsHbqvxyyePCmaoGCZJduGhc5akOz4nF9gmC+uDp9otclct
tjRkzwhKM30wN5YDUiHJkQ/ODRr0KWtrU8MwxRmIK1wy/RbqR6flWIuame1JnM7l
rp3ZZfC0cQcjA6AtHSbGYjlaYolPS2pHKXK+TQ/5CQDUs7HMDxnlItApzBr44ltB
hHfT6QWEhmA96DcGF2U2WkHTlFz9DLJim8hAwnZKCQNs4cnChPEZ0DyZE1meWkx6
vZqwgRm0evd0VQctFu+jcmpG1P/hxEjmnnpbOMsWe88nwoVSUp10675xH7mNzzX/
jnM9SZgFW1BvsRdMf5T10FNAa048jXDa
-----END ENCRYPTED PRIVATE KEY-----
"
      private_key_passphrase: secret

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
